

spring:
  profiles:
    active: prod

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: foodService



# It tells our service where to read its configs from, in this case the Url of Config server.
# We wrote optional just to tell it is not necessary to read from there only.
# Incase our configServer is down, it helps, we can read the configs from our folder itself.
  config:
    import: "optional:configserver:http://localhost:9095/"

  datasource:
    url: jdbc:mysql://localhost:3306/lcwd
    username: root
    password: Restinpeace11.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
 # Enables all the actuator endpoints.
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true


resilience4j:
  circuitbreaker:
    configs:
      # By default it means that this configuration will be applied to all the cicuit breaker patterns.
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

server:
  port: 9092
